[package]
name = "oghscan"
edition.workspace = true
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
sqlitedb = { path = "../sqlitedb" }
serde.workspace = true
serde_json.workspace = true
reqwest.workspace = true
tokio.workspace = true
url.workspace = true
cached.workspace = true
lazy_static.workspace = true
regex.workspace = true
tokio-rustls = "0.26"
rustls = { version = "0.23", default-features = false, features = ["std", "ring", "tls12"] }
webpki-roots = "1"
x509-parser = "0.16"
